@startuml 画面遷移

hide empty description
left to right direction
title 画面遷移

[*] -down-> ログイン
ログイン --> 新規登録
新規登録 --> ログイン
ログイン --> タイムライン
タイムライン --> プロフィール
タイムライン --> ポスト
ポスト --> タイムライン
プロフィール --> タイムライン
プロフィール --> プロフィール編集
プロフィール編集 --> プロフィール

@enduml
